<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>bin\$(Configuration)\net6.0\</OutputPath>
    <RapidTransitDeployDir>$(UserProfile)\AppData\LocalLow\Colossal Order\Cities Skylines II\Mods\RapidTransitMod</RapidTransitDeployDir>
    <PublishConfigurationPath>Properties\PublishConfiguration.xml</PublishConfigurationPath>
    <EnableOfficialToolchain>false</EnableOfficialToolchain>
    <OfficialToolPath>$([System.Environment]::GetEnvironmentVariable('CSII_TOOLPATH', 'EnvironmentVariableTarget.User'))</OfficialToolPath>
    <OfficialToolPath Condition="'$(OfficialToolPath)'==''">D:\steam\steamapps\common\Cities Skylines II\Cities2_Data\Content\Game\.ModdingToolchain</OfficialToolPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>$(DefineConstants);RT_DEBUG_TOOLS;RT_VERBOSE_LOGS</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>$(DefineConstants);RT_RELEASE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="references\**\*.cs" />
    <Compile Remove="tools\**\*.cs" />
    <None Include="references\**\*.cs" />
    <None Include="rapidtransit-ui-module\dist\RapidTransitMod.mjs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>RapidTransitMod.mjs</TargetPath>
    </None>
    <None Include="UI\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>UI\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </None>
    <None Include="workbench-app\workbench-dist\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>UI\workbench\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </None>
    <None Include="workbench-app\workbench-dist\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>UI\workbench-app\dist\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </None>
    <None Include="Locales\**\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>Locales\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
    </None>
    <None Include="mod.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AssetDatabase.TestScenarios">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\AssetDatabase.TestScenarios.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colossal.Core">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.Core.dll</HintPath>
    </Reference>
    <Reference Include="Colossal.AssetPipeline">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.AssetPipeline.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colossal.IO.AssetDatabase">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.IO.AssetDatabase.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colossal.Logging">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.Logging.dll</HintPath>
    </Reference>
    <Reference Include="Colossal.ATL">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.ATL.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colossal.Localization">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.Localization.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colossal.Mathematics">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.Mathematics.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colossal.UI.Binding">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.UI.Binding.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Colossal.UI">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Colossal.UI.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Game">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Game.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="cohtml.Net">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\cohtml.Net.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Burst">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Unity.Burst.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Collections">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Unity.Collections.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Entities">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Unity.Entities.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Unity.Mathematics">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\Unity.Mathematics.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.AudioModule">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\UnityEngine.AudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestModule">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\UnityEngine.UnityWebRequestModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="UnityEngine.UnityWebRequestAudioModule">
      <HintPath>..\..\steam\steamapps\common\Cities Skylines II\Cities2_Data\Managed\UnityEngine.UnityWebRequestAudioModule.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="System.Runtime.Serialization" />
  </ItemGroup>

  <Target Name="DeployRapidTransitMod" AfterTargets="Build">
    <Delete Files="$(OutputPath)0Harmony.dll" ContinueOnError="true" />
    <Delete Files="$(RapidTransitDeployDir)\0Harmony.dll" ContinueOnError="true" />
    <ItemGroup>
      <RapidTransitDeployFiles Include="$(OutputPath)RapidTransitMod.dll" />
      <RapidTransitDeployFiles Include="$(OutputPath)RapidTransitMod.pdb" />
      <RapidTransitDeployFiles Include="$(OutputPath)RapidTransitMod.mjs" />
      <RapidTransitDeployFiles Include="$(OutputPath)mod.json" />
    </ItemGroup>
    <ItemGroup>
      <RapidTransitDeployUiFiles Include="$(OutputPath)UI\**\*" />
      <RapidTransitDeployLocaleFiles Include="$(OutputPath)Locales\**\*.json" />
    </ItemGroup>
    <MakeDir Directories="$(RapidTransitDeployDir)" />
    <Copy SourceFiles="@(RapidTransitDeployFiles)" DestinationFolder="$(RapidTransitDeployDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(RapidTransitDeployUiFiles)" DestinationFiles="@(RapidTransitDeployUiFiles->'$(RapidTransitDeployDir)\UI\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(RapidTransitDeployLocaleFiles)" DestinationFiles="@(RapidTransitDeployLocaleFiles->'$(RapidTransitDeployDir)\Locales\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

  <Import Project="$(OfficialToolPath)\Mod.props" Condition="'$(EnableOfficialToolchain)'=='true' and Exists('$(OfficialToolPath)\Mod.props')" />
  <Import Project="$(OfficialToolPath)\Mod.targets" Condition="'$(EnableOfficialToolchain)'=='true' and Exists('$(OfficialToolPath)\Mod.targets')" />

</Project>
